In [8]:
item_list=['bread','milk','egg','butter','cocoa']
student_marks = [78,47,96,55,34]
hetero_list = [1,2,3.0, 'text',True,3+2j]
print(item_list)
print(student_marks)
print(hetero_list)

['bread', 'milk', 'egg', 'butter', 'cocoa']
[78, 47, 96, 55, 34]
[1, 2, 3.0, 'text', True, (3+2j)]


In [9]:
student_marks = [78,47,96,55,34]
for i in range(len(student_marks)):
    student_marks[i]+=5
print(student_marks)

[83, 52, 101, 60, 39]


In [10]:
%%time
list1 = list(range(1,1000000))
list2 = list(range(2,1000001))
list3 = []
for i in range (len(list1)):
    list3.append(list1[i]+list2[i])

CPU times: total: 453 ms
Wall time: 642 ms


In [16]:
%%time
import numpy as np
a = np.arange(1,1000000)
b = np.arange(2,1000001)
c = a+b


CPU times: total: 0 ns
Wall time: 10.2 ms


In [17]:
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
car_attributes_arr = np.array(car_attributes)
car_attributes_arr


array([[ 18,  15,  18,  16,  17],
       [130, 165, 150, 150, 140],
       [307, 350, 318, 304, 302]])

In [18]:
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
car_attributes_arr = np.array(car_attributes)
car_attributes_arr.shape


(3, 5)

In [20]:
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]] 
car_attributes_arr = np.array(car_attributes, dtype = 'float')
print(car_attributes_arr)
print(car_attributes_arr.dtype)


[[ 18.  15.  18.  16.  17.]
 [130. 165. 150. 150. 140.]
 [307. 350. 318. 304. 302.]]
float64


In [4]:
cars = np.array(['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino'])
cars[1


SyntaxError: incomplete input (2439566273.py, line 2)

In [5]:
import numpy as np

cars = np.array(['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino'])

# Accessing the second car from the array (remember that indexing is 0-based)
second_car = cars[1]
print(second_car)


buick skylark 320


In [6]:

car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
car_hp_arr = np.array([car_names, horsepower])
car_hp_arr


array([['chevrolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino'],
       ['130', '165', '150', '150', '140']], dtype='<U25')

In [7]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
car_hp_arr = np.array([car_names, horsepower])
car_hp_arr[0]


array(['chevrolet chevelle malibu', 'buick skylark 320',
       'plymouth satellite', 'amc rebel sst', 'ford torino'], dtype='<U25')

In [8]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
car_hp_arr = np.array([car_names, horsepower])
car_hp_arr[0,-1]


'ford torino'

In [9]:
cars = np.array(['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino'])
#accessing a subset of cars from the array
cars[1:5]


array(['buick skylark 320', 'plymouth satellite', 'amc rebel sst',
       'ford torino'], dtype='<U25')

In [10]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
acceleration = [18, 15, 18, 16, 17]
car_hp_acc_arr = np.array([car_names, horsepower, acceleration])
car_hp_acc_arr


array([['chevrolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino'],
       ['130', '165', '150', '150', '140'],
       ['18', '15', '18', '16', '17']], dtype='<U25')

In [11]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
acceleration = [18, 15, 18, 16, 17]
car_hp_acc_arr = np.array([car_names, horsepower, acceleration])
car_hp_acc_arr[0:2]


array([['chevrolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino'],
       ['130', '165', '150', '150', '140']], dtype='<U25')

In [12]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
acceleration = [18, 15, 18, 16, 17]
car_hp_acc_arr = np.array([car_names, horsepower, acceleration])
car_hp_acc_arr[0:2, 3:5]


array([['amc rebel sst', 'ford torino'],
       ['150', '140']], dtype='<U25')

In [19]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
acceleration = [18, 15, 18, 16, 17]
car_hp_acc_arr = np.array([car_names, horsepower, acceleration])
car_hp_acc_arr[0:3, 4:5]


array([['ford torino'],
       ['140'],
       ['17']], dtype='<U25')

In [ ]:
#Creating a 2D array consisting car names, horsepower and acceleration
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
acceleration = [18, 15, 18, 16, 17]
car_hp_acc_arr = np.array([car_names, horsepower, acceleration])
#Accessing name, horsepower and acceleration of first three cars
car_hp_acc_arr[0:3, 0:3]


In [21]:
horsepower = [130,165,150,15,140]
horsepower_arr = np.array(horsepower)
print("Mean horsepower = ",np.mean(horsepower_arr))

Mean horsepower =  120.0


In [23]:
horsepower = [130,165,150,150,140]
horsepower_arr = np.array(horsepower)
print("median horsepower = ",np.median(horsepower_arr))

median horsepower =  150.0


In [24]:
horsepower_arr=np.array([130,165,150,150,140])
mean_arr=np.mean(horsepower_arr)
mean_arr

147.0

In [25]:
horsepower_arr=np.array([130,165,150,150,140])
median_arr=np.median(horsepower_arr)
median_arr

150.0

In [28]:



horsepower_arr = np.array([130, 165, 150, 150, 140])
Minimum_arr =np.min(horsepower_arr)
Maximum_arr =np.max(horsepower_arr)
print(Minimum_arr)
print(Maximum_arr)

130
165


In [7]:
import numpy as np
stepwalked=np.array([[1,6012],[2,7079],[3,6886],[4,7230,],[5,4598],[6,5564],[7,6971],[8,7763],[9,8032],[10,9569]])

steps=([[6012],[7079],[6886],[7230,],[4598],[5564],[6971],[7763],[8032],[9569]])
print(stepwalked)

averagesteps=([0,2000])
totalsteps=np.add(stepwalked,averagesteps)
print(totalsteps)

x=np.where(totalsteps[:,1] > 9000)
print(totalsteps[x])
sort=np.sort(totalsteps)
print(sort)

[[   1 6012]
 [   2 7079]
 [   3 6886]
 [   4 7230]
 [   5 4598]
 [   6 5564]
 [   7 6971]
 [   8 7763]
 [   9 8032]
 [  10 9569]]
[[    1  8012]
 [    2  9079]
 [    3  8886]
 [    4  9230]
 [    5  6598]
 [    6  7564]
 [    7  8971]
 [    8  9763]
 [    9 10032]
 [   10 11569]]
[[    2  9079]
 [    4  9230]
 [    8  9763]
 [    9 10032]
 [   10 11569]]
[[    1  8012]
 [    2  9079]
 [    3  8886]
 [    4  9230]
 [    5  6598]
 [    6  7564]
 [    7  8971]
 [    8  9763]
 [    9 10032]
 [   10 11569]]


In [8]:
import numpy as np

stepwalked = np.array([[1, 6012], [2, 7079], [3, 6886], [4, 7230], [5, 4598], [6, 5564], [7, 6971], [8, 7763], [9, 8032], [10, 9569]])

# Adding 2000 steps after 7 pm
average_steps = np.array([0, 2000])
total_steps = stepwalked + average_steps

# Filtering and printing steps walked more than 9000
steps_above_9000 = total_steps[total_steps[:, 1] > 9000]
print("Steps walked more than 9000:", steps_above_9000)

# Sorting the steps walked in ascending order
sorted_steps = np.sort(total_steps[:, 1])
print("Sorted steps walked:", sorted_steps)


Steps walked more than 9000: [[    2  9079]
 [    4  9230]
 [    8  9763]
 [    9 10032]
 [   10 11569]]
Sorted steps walked: [ 6598  7564  8012  8886  8971  9079  9230  9763 10032 11569]


In [12]:
import numpy as np
stepwalked=np.array([[1,6012],[2,7079],[3,6886],[4,7230,],[5,4598],[6,5564],[7,6971],[8,7763],[9,8032],[10,9569]])

steps=([[6012],[7079],[6886],[7230,],[4598],[5564],[6971],[7763],[8032],[9569]])
print(stepwalked)

averagesteps=([0,2000])
totalsteps=np.add(stepwalked,averagesteps)
print(totalsteps)

x=np.where(totalsteps[:,1] > 9000)
print(totalsteps[x])

sorted_steps = np.sort(total_steps[:, 1])
sorted_steps_column = sorted_steps.reshape(-1, 1)
print("Sorted steps walked:\n", sorted_steps_column)


[[   1 6012]
 [   2 7079]
 [   3 6886]
 [   4 7230]
 [   5 4598]
 [   6 5564]
 [   7 6971]
 [   8 7763]
 [   9 8032]
 [  10 9569]]
[[    1  8012]
 [    2  9079]
 [    3  8886]
 [    4  9230]
 [    5  6598]
 [    6  7564]
 [    7  8971]
 [    8  9763]
 [    9 10032]
 [   10 11569]]
[[    2  9079]
 [    4  9230]
 [    8  9763]
 [    9 10032]
 [   10 11569]]
Sorted steps walked:
 [[ 6598]
 [ 7564]
 [ 8012]
 [ 8886]
 [ 8971]
 [ 9079]
 [ 9230]
 [ 9763]
 [10032]
 [11569]]


In [7]:
import numpy as np
stepwalked=np.array([[1,6012],[2,7079],[3,6886],[4,7230,],[5,4598],[6,5564],[7,6971],[8,7763],[9,8032],[10,9569]])

steps=([[6012],[7079],[6886],[7230,],[4598],[5564],[6971],[7763],[8032],[9569]])
print(stepwalked)

averagesteps=([0,2000])
totalsteps=np.add(stepwalked,averagesteps)
print(totalsteps)

x=np.where(totalsteps[:,1] > 9000)
print(totalsteps[x])

cc = totalsteps[:,1].argsort()
totalsteps[cc]

[[   1 6012]
 [   2 7079]
 [   3 6886]
 [   4 7230]
 [   5 4598]
 [   6 5564]
 [   7 6971]
 [   8 7763]
 [   9 8032]
 [  10 9569]]
[[    1  8012]
 [    2  9079]
 [    3  8886]
 [    4  9230]
 [    5  6598]
 [    6  7564]
 [    7  8971]
 [    8  9763]
 [    9 10032]
 [   10 11569]]
[[    2  9079]
 [    4  9230]
 [    8  9763]
 [    9 10032]
 [   10 11569]]


array([[    5,  6598],
       [    6,  7564],
       [    1,  8012],
       [    3,  8886],
       [    7,  8971],
       [    2,  9079],
       [    4,  9230],
       [    8,  9763],
       [    9, 10032],
       [   10, 11569]])