In [3]:
import numpy as np 
hr_array=np.array([130,165,150,150,140])
x=np.where(hr_array>=150)
print(x)
print(hr_array[x])

(array([1, 2, 3], dtype=int64),)
[165 150 150]


In [12]:
numpy=np.array([[67,45],[90,92],[66,72],[32,40]])
print(numpy)

[[67 45]
 [90 92]
 [66 72]
 [32 40]]


In [11]:
numpy=np.array([[67,45],[90,92]]),([66,72],[32,40])
print(numpy)

(array([[67, 45],
       [90, 92]]), ([66, 72], [32, 40]))


In [16]:
numpy=np.array([[67,45],[90,92],[66,72],[32,40]])
numpy1=([5,10])
numpy2=np.add(numpy,numpy1)
print(numpy2)

[[ 72  55]
 [ 95 102]
 [ 71  82]
 [ 37  50]]


In [25]:
np.arange(2,100000,2)

array([    2,     4,     6, ..., 99994, 99996, 99998])

In [31]:
arr = np.linspace(0,000,500)
print(arr)
print('Length of arr: ',len(arr))


[   0.            4.00801603    8.01603206   12.0240481    16.03206413
   20.04008016   24.04809619   28.05611222   32.06412826   36.07214429
   40.08016032   44.08817635   48.09619238   52.10420842   56.11222445
   60.12024048   64.12825651   68.13627255   72.14428858   76.15230461
   80.16032064   84.16833667   88.17635271   92.18436874   96.19238477
  100.2004008   104.20841683  108.21643287  112.2244489   116.23246493
  120.24048096  124.24849699  128.25651303  132.26452906  136.27254509
  140.28056112  144.28857715  148.29659319  152.30460922  156.31262525
  160.32064128  164.32865731  168.33667335  172.34468938  176.35270541
  180.36072144  184.36873747  188.37675351  192.38476954  196.39278557
  200.4008016   204.40881764  208.41683367  212.4248497   216.43286573
  220.44088176  224.4488978   228.45691383  232.46492986  236.47294589
  240.48096192  244.48897796  248.49699399  252.50501002  256.51302605
  260.52104208  264.52905812  268.53707415  272.54509018  276.55310621
  280.